#!/bin/bash
touch input
rm results -f
min_difficulty=$((2 ** 62))
readarray -t words < input
declare -A keyboard
keyboard=([1]=0 [2]=2 [3]=4 [4]=6 [5]=8 [6]=10 [7]=12 [8]=14 [9]=16 [0]=18 \
[a]=20 [z]=22 [e]=24 [r]=26 [t]=28 [y]=30 [u]=32 [i]=34 [o]=36 [p]=38 \
[A]=20 [Z]=22 [E]=24 [R]=26 [T]=28 [Y]=30 [U]=32 [I]=34 [O]=36 [P]=38 \
[q]=40 [s]=42 [d]=44 [f]=46 [g]=48 [h]=50 [j]=52 [k]=54 [l]=56 [m]=58 \
[Q]=40 [S]=42 [D]=44 [F]=46 [G]=48 [H]=50 [J]=52 [K]=54 [L]=56 [M]=58 \
[w]=63 [x]=65 [c]=67 [v]=69 [b]=71 [n]=73 [.]=77 \
[W]=63 [X]=65 [C]=67 [V]=69 [B]=71 [N]=73)

for ((n=0; n < ${#words[@]}; n++)); do
  word=${words[n]}
  difficulty=0
  for ((i=0; i < ${#word}-1; i++)); do
    id1=${keyboard[''${word:i:1}'']}
    id2=${keyboard[''${word:i+1:1}'']}
    ((difficulty+=$((((($id1/20 - $id2/20) * 2 ) ** 2) + (($id1%20 - $id2%20) ** 2)))))
  done
  if (( $difficulty < $min_difficulty )); then
    min_difficulty=$difficulty
  fi
  if (( $difficulty-10 < $min_difficulty )); then
    echo "$difficulty > $word"
  fi
done
