#!/bin/bash

main() {

  touch results
  rm results
  keyboard=(a z e r t y u i o p q s d f g h j k l m - w x c v b n - . -)
  readarray -t domains < char
  line=0
  updater &

  for each in "${domains[@]}"; do

    for (( i=0 ; i < "${#domains[line]}" ; i++ )); do letters[i]="${domains[line]:i:1}"; done
    letter=0
    typelenght=0

    for (( i = 1; i < "${#letters[@]}"; i++ )); do

      id1=0
      for x in "${keyboard[@]}"; do
        if [[ "${keyboard[id1]}" = "${letters[letter]}" ]]; then
          break
        fi
        ((id1++))
      done

      id2=0
      for x in "${keyboard[@]}"; do
        if [[ "${keyboard[id2]}" = "${letters[letter+1]}" ]]; then
          break
        fi
        ((id2++))
      done

      if (( id1 >= 20 )); then
        id1=`echo "$id1+0.5" | bc`
      fi
      if (( id2 >= 20 )); then
        id2=`echo "$id2+0.5" | bc`
      fi

      x1=`echo "$id1%10" | bc`
      x2=`echo "$id2%10" | bc`
      if (( `echo "$x1/1" | bc` >= `echo "$x2/1" | bc` )); then
        x=`echo "squale=1; $x1-$x2" | bc`
      else
        x=`echo "squale=1; $x2-$x1" | bc`
      fi

      y1=`echo "$id1/10" | bc`
      y2=`echo "$id2/10" | bc`
      y=`echo "$y1-$y2" | bc `

      distance=`echo "scale=2; sqrt($x^2+$y^2)" | bc`
      typelenght=`echo "scale=2; $typelenght+$distance" | bc`
      ((letter++))

    done
#    echo "$typelenght > ${domains[line]}"
    printf "$typelenght > ${domains[line]}\n" >> results
    ((line++))

  done

}

updater() {
  while true; do
    sleep 5
    clear
    cat results | sort -g | head -n 100
  done
}

main
